server:
  port: 9040
spring:
  application:
    name: "messageService"
  mail:
    host: smtp.gmail.com
    port: 587
    username: "xxxxxxxxxxxxxxxxxx"
    password: "xxxx xxxx xxxx xxxx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    function:
      definition: sendEmails
    stream:
      bindings:
        sendEmails-in-0:
          destination: email-communication
          group: ${spring.application.name}

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  connection-timeout: 10s

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

